#include <stdint.h>

/// Define frequency Lora + SD
#define LORA_FREQ 915E6 /// 915MHz frequency for Lora
#define SD_RATE 20E6    /// 20MHz rate for SD 

const uint8_t MAX_GPS_BYTES_PER_LOOP = 64;  
const uint8_t GPS_TIMEOUT = 200;
const uint8_t ADXL_SAMPLES_MAX = 20; 
const uint8_t LSM_SAMPLES_MAX = 20;
const uint8_t BMP_SAMPLES_MAX = 20; 

const uint8_t ACCEL_LAUNCH_G = 2; 
const float GRAVITY_FORCE = 9.80665;
const float JUNO_MAX_SPEED = 301.483;
const uint8_t REQ_COUNT_STATE_CHANGE = 3;
const float BMP_DATA_RATE = 0.0355;
const float BMP_STANDARD_DEVIATION = 0.07594;
const uint8_t BMP_NOISE_MULTIPLIER = 3;
const uint8_t BMP_DESCEND_THRESHOLD = 20;
const float ASCEND_THRESHOLD = GRAVITY_FORCE * ACCEL_LAUNCH_G;
const float BMP_STEP_MAX = JUNO_MAX_SPEED * BMP_DATA_RATE;
const float BMP_NOISE_THRESHOLD = BMP_STANDARD_DEVIATION * BMP_NOISE_MULTIPLIER;
const uint8_t BMP_LAND_THRESHOLD = 41;
const float ADXL_MAGNITUDE_STANDARD_DEVIATION = 0.698823;
const float LSM_MAGNITUDE_STANDARD_DEVIATION = 0.0005284;
const float LAND_NOISE_MULTIPLIER = 3.5;
const float ADXL_LAND_THRESHOLD = ADXL_MAGNITUDE_STANDARD_DEVIATION * LAND_NOISE_MULTIPLIER;
const float LSM_LAND_THRESHOLD = LSM_MAGNITUDE_STANDARD_DEVIATION * LAND_NOISE_MULTIPLIER;
const uint16_t LAND_COUNTER_MAX = 300;